[build]
  command = "quarto render ."
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.4.550"

[[build.lifecycle]]
  name = "Install Quarto"
  lifecycle = "install"
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz
    tar -xzf quarto-${QUARTO_VERSION}-linux-amd64.tar.gz
    export PATH=$PATH:$(pwd)/quarto-${QUARTO_VERSION}/bin
  """
