[build]
  command = "quarto render"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.4.550"

[[build.lifecycle]]
  name = "Install Quarto"
  lifecycle = "beforeInstall"
  command = """
    curl -L -o quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.deb
    sudo dpkg -i quarto.deb
  """
